# Generated by Django 5.1.4 on 2025-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('idexp', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreexp', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('precioeur', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'experiencia',
            },
        ),
    ]
